COLUMNS_DICT = {
    "RowNumber": "Row numbers from 1 to 10000",
    "CustomerId": "Unique IDs for bank customer identification",
    "Surname": "Customer's last name",
    "CreditScore": "Credit score of the customer",
    "Geography": "The country from which the customer belongs",
    "Gender": "Male or Female",
    "Age": "Age of the customer",
    "Tenure": "Number of years for which the customer has been with the bank",
    "Balance": "Bank balance of the customer",
    "NumOfProducts": "Number of bank products the customer is utilising",
    "HasCrCard": "Binary flag for whether the customer holds a credit card with the bank or not",
    "IsActiveMember": "Binary flag for whether the customer is an active member with the bank or not",
    "EstimatedSalary": "Estimated salary of the customer in dollars",
    "Customer ID": "Unique identifier for each customer.",
    "Item Purchased": "Name of the item purchased.",
    "Category": "Product category (Clothing, Footwear, Outerwear, Accessories).",
    "Purchase Amount (USD)": "Total amount spent on the purchase.",
    "Location": "Geographic location of the customer (city)",
    "Size": "Size of the item purchased (if applicable; e.g., S, M, L, XL).",
    "Color": "Color of the item purchased",
    "Season": "Season of the purchase (e.g., Winter, Summer, Spring, Fall).",
    "Review Rating": "Customer's review rating for the purchase (e.g., 1-5 stars).",
    "Subscription Status": "Indicates whether the customer is a subscriber (e.g., Active, Inactive, None).",
    "Payment Method": "Method used for the payment (e.g., Credit Card, PayPal, Cash, Venmo, Debit Card, Bank Transfer).",
    "Shipping Type": "Type of shipping chosen (Express, Free Shipping, Next Day Air, Standard, 2-Day Shipping, Store Pickup)",
    "Discount Applied": "Indicates if a discount was applied (e.g., Yes/No).",
    "Promo Code Used": "Specifies if a promo code was used during the purchase (e.g., Yes/No).",
    "Previous Purchases": "Total number of previous purchases made by the customer.",
    "Preferred Payment Method": "The payment method most frequently used by the customer.",
    "Frequency of Purchases": "How often the customer makes purchases.",
    "Date": "The date corresponding to each financial record (from January 2015 onwards).",
    "Operating_Income": "The income generated from the bank's core business operations.",
    "Expenses": "Total costs incurred during operations.",
    "Net_Income": "Profit after subtracting expenses from operating income.",
    "Assets": "Total assets owned by the bank (e.g., cash, investments).",
    "Liabilities": "The total debts and obligations owed.",
    "Equity": "Shareholders' equity, representing the net value of assets minus liabilities.",
    "Debt_to_Equity": "A financial ratio showing the proportion of debt compared to equity.",
    "ROA": "A profitability metric calculated as net income divided by total assets.",
    "Revenue": "Total income from all operations and activities.",
    "Cash_Flow": "The net cash generated or used in operations.",
    "Profit_Margin": "A ratio showing the percentage of revenue that remains as profit.",
    "Interest_Expense": "Costs associated with the bank's borrowings or debts.",
    "Tax_Expense": "The amount paid as taxes on profits.",
    "Dividend_Payout": "The portion of earnings distributed to shareholders as dividends.",
     "Order No": "Unique identifier for the order",
    "Order Time": "Timestamp when the order was placed",
    "Order Type": "Type of order (e.g., Dine-in, Takeaway, Delivery)",
    "Order Taken By": "Name or ID of the staff who took the order",
    "Customer Name": "Full name of the customer",
    "Customer Number": "Contact number of the customer",
    "Item Name": "Name of the purchased item",
    "Quantity": "Number of units of the item ordered",
    "Item Type": "Category of the item (e.g., Beverage, Main Course, Dessert)",
    "Price": "Cost of the item before tax and discounts",
    "Item Tax": "Applicable tax amount on the item",
    "Item Discount": "Discount applied to the item, if any"
    }
